CREATE TABLE Measurements(
	Id SERIAL PRIMARY KEY,
	Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Heat1 BOOLEAN NOT NULL,
	Heat2 BOOLEAN NOT NULL,
	Fan1 TINYINT NOT NULL,
	Fan2 TINYINT NOT NULL,
	TargetTemp DECIMAL(3,2) NOT NULL,
	CurrentTemp DECIMAL(3,2) NOT NULL,
	CurrentHumidity DECIMAL(3,2) NOT NULL
);
